# Generated by Django 5.2.5 on 2025-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_fix_json_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, help_text='Structured data about the action (stored as JSON string)', null=True, verbose_name='Action Details'),
        ),
    ]
